### PR TITLE
Configuration hot reload

### LINKED ISSUE #95: Have to restart process after registering an API
I perform a POST /apis and register an upstream. I then try and use the route I just registered, but the debug log shows no activity at all.

I then kill and restart Janus, and then try and use the route, and it works.

This looks like a duplicate of #84, which for some reason was closed without a fix.

**Reproduction Steps:**

1. Register an upstream via POST /API using a <unique_listenpath>
2. curl localhost:8080/<unique_listenpath> and see 404
3. Restart Janus, then retry previous step number 2 which will now work

**Expected behavior:**

Upstreams work after registration without a restart required.

**Janus version:** [1.7.4-rc.6](https://github.com/hellofresh/janus/releases/tag/1.7.4-rc.6)

### PR DESCRIPTION
**Pull request by italolelis**
## What does this PR do?

* Adds the ability to hot reload proxy definitions. To enable this feature you MUST use Redis as your datastore. If you use in memory storage this feature will not be enabled. This fixes #95 
* Adds a bunch of tests.
* Added the ability to enable or disable plugins per API definitions. This will bring us a lot of flexibility in developing new plugins and hooking them up. This feature is a BC and we should upgrade the major version because of that. 
* Using viper to load the API definitions when using file based configurations. This allows you to configure your API definitions in YAML, JSON and TOML.

### CODE REVIEW

File: pkg/api/api_test.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package api_test
```
Comment (vgarvardt) [inline pkg/api/api_test.go:1]: wrong package?

File: pkg/api/api_test.go [hunk 2]
```diff
@@ -0,0 +1,20 @@
...
+	"github.com/hellofresh/janus/pkg/api"
+	"github.com/stretchr/testify/assert"
+)
+
+const (
+	testKey   = "key"
+	testValue = "value"
+)
+
+func TestNewInstanceOfDefinition(t *testing.T) {
```
Comment (vgarvardt) [inline pkg/api/api_test.go:15]: IntelliJ Gogland suggest the following names for tests (and I like it, although it is not necessary):
* `Test<FunctionName>()` for functions
* `Test<StructName>_<MethodName>()` for struct methods

With the naming like this it is easier to track what it tests.

File: pkg/api/file_repository.go [hunk 3]
```diff
@@ -20,28 +20,39 @@ type FileSystemRepository struct {
...
-				log.WithError(err).WithField("path", filePath).Error("Couldn't load the api definition file")
-				return nil, err
+		filePath := filepath.Join(dir, f.Name())
+		definition := new(Definition)
+
+		v := viper.New()
+		v.SetConfigFile(filePath)
+		v.WatchConfig()
+		v.OnConfigChange(func(e fsnotify.Event) {
+			log.Debug("API configuration changed, reloading...")
```
Comment (vgarvardt) [inline pkg/api/file_repository.go]: `log.WithFields(log.Fields("name": e.Name, "op": e.Op.String()}).Debug("API configuration changed, reloading...")`

File: pkg/api/file_repository.go [hunk 4]
```diff
@@ -20,28 +20,39 @@ type FileSystemRepository struct {
...
+			if err := v.Unmarshal(definition); err != nil {
```
Comment (vgarvardt) [inline pkg/api/file_repository.go]: `e.Op` can be `Remove`, then no need to unmarshal, or `Rename`, then I do not know if `viper` handles this properly and re-reads new file. I think you should leave only logging part for now and implement this in `hot-reload` feature.

File: pkg/loader/api_loader.go [hunk 5]
```diff
@@ -0,0 +1,115 @@
...
+	}
+}
+
+// RegisterAPI register an API Spec in the register
+func (m *APILoader) RegisterAPI(referenceSpec *api.Spec) {
+	logger := log.WithField("api_name", referenceSpec.Name)
+
+	active, err := referenceSpec.Validate()
+	if false == active && err != nil {
+		logger.WithField("errors", err.Error()).Warn("Validation errors")
```
Comment (vgarvardt) [inline pkg/loader/api_loader.go]: `WithError(err)`

File: pkg/loader/api_loader.go [hunk 6]
```diff
@@ -0,0 +1,115 @@
...
+		active = false
+	}
+
+	if active {
+		var handlers []router.Constructor
+
+		for pName, pDefinition := range referenceSpec.Plugins {
+			pDefinition.Name = pName
+			if pDefinition.Enabled {
+				logger.Debugf("Plugin %s enabled", pName)
```
Comment (vgarvardt) [inline pkg/loader/api_loader.go]: `logger.WithField("name", pName).Debug("Plugin enabled")`

File: pkg/loader/api_loader.go [hunk 7]
```diff
@@ -0,0 +1,115 @@
...
+							WithField("plugin_name", pName).
+							Error("Error loading plugin")
+					}
+
+					for _, mw := range middlewares {
+						handlers = append(handlers, mw)
+					}
+				}
+			} else {
+				logger.Debugf("Plugin %s not enabled", pName)
```
Comment (vgarvardt) [inline pkg/loader/api_loader.go]: `logger.WithField("name", pName).Debug("Plugin not enabled") `

File: pkg/loader/api_loader.go [hunk 8]
```diff
@@ -0,0 +1,115 @@
...
+			}
+		}
+
+		m.register.Add(proxy.NewRoute(referenceSpec.Proxy, handlers...))
+		logger.Debug("API registered")
+	} else {
+		logger.Warn("API URI is invalid or not active, skipping...")
```
Comment (vgarvardt) [inline pkg/loader/api_loader.go]: I think we should add `WithError(err)` here, then it will clear in log if it is invalid or not active

File: pkg/loader/api_loader_test.go [hunk 9]
```diff
@@ -1,15 +1,15 @@
-package api_test
+package loader_test
```
Comment (vgarvardt) [inline pkg/loader/api_loader_test.go]: `package loader`

File: pkg/middleware/host_matcher_test.go [hunk 10]
```diff
@@ -0,0 +1,84 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/host_matcher_test.go]: `package middleware`

File: pkg/middleware/logger_test.go [hunk 11]
```diff
@@ -0,0 +1,27 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/logger_test.go]: `package middleware`

File: pkg/middleware/opentracing_test.go [hunk 12]
```diff
@@ -0,0 +1,27 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/opentracing_test.go]: `package middleware`

File: pkg/middleware/rate_limit_logger_test.go [hunk 13]
```diff
@@ -0,0 +1,27 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/rate_limit_logger_test.go]: `package middleware`

File: pkg/middleware/recovery_test.go [hunk 14]
```diff
@@ -0,0 +1,33 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/recovery_test.go]: `package middleware`

File: pkg/middleware/stats_test.go [hunk 15]
```diff
@@ -0,0 +1,28 @@
+package middleware_test
```
Comment (vgarvardt) [inline pkg/middleware/stats_test.go]: `package middleware`

File: pkg/oauth/file_repository.go [hunk 16]
```diff
@@ -28,21 +28,31 @@ func NewFileSystemRepository(dir string) (*FileSystemRepository, error) {
...
-				log.WithError(err).WithField("path", filePath).Error("Couldn't load oauth server definition file")
-				return nil, err
+		filePath := filepath.Join(dir, f.Name())
+		definition := new(OAuth)
+
+		v := viper.New()
+		v.SetConfigFile(filePath)
+		v.WatchConfig()
+		v.OnConfigChange(func(e fsnotify.Event) {
+			log.Debug("OAauth2 configuration changed, reloading...")
```
Comment (vgarvardt) [inline pkg/oauth/file_repository.go]: same comments as for routes hot reloading

**Review by vgarvardt — CHANGES_REQUESTED** [review]

File: pkg/api/api_test.go (hunk 1 above)
Comment (italolelis) [reply pkg/api/api_test.go:1]: nope. This is the test suffix only... This makes sure that you don't load test functions to your binary when compiling

File: pkg/loader/api_loader_test.go (hunk 9 above)
Comment (italolelis) [reply pkg/loader/api_loader_test.go]: it's `loader_test`

File: pkg/store/store.go [hunk 17]
```diff
@@ -39,6 +47,22 @@ type Options struct {
 	CleanUpInterval time.Duration
 }
 
+// Message represents the message that comes
+// form an update
```
Comment (rafaeljesus) [inline pkg/store/store.go]: typo `from`

File: docs/plugins/rate_limit.md [hunk 18]
```diff
@@ -0,0 +1,45 @@
...
+
+## Configuration
+
+Configuring the plugin is straightforward, you can add it on top of an API by executing the following request on your Janus server:
+
+| Configuration | Description                                                                                                                                                                                                                                            |
+|---------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
+| limit         | Defines the limit rule for the proxy. i.e. "10-S", means 10 req/s                                                                                                                                                                                      |
```
Comment (vgarvardt) [inline docs/plugins/rate_limit.md]: I could not find format for this field, only one sample in description for `10 req/s`. How do I do `15 req/min`, `100 req/h`, `10000 req/day`? If this supports only `req/s` then `-S` suffix is redundant, if it supports all types of limits that I mentioned - we need a description for this or a link to a format description.

File: README.md [hunk 19]
```diff
@@ -51,7 +51,7 @@ This API Gateway offers powerful, yet lightweight features that allows fine gain
 
 ### Docker
 
-The simplest way of installing janus is to run the docker image for it. Just check the [docker-compose.yml](ci/assets/docker-compose.yml)
+The simplest way of installing janus is to run the docker image for it. Just check the [docker-compose.yml](docker-compose.yml)
```
Comment (vgarvardt) [inline README.md]: All other docs has `janus` capitalised.

File: docs/quick_start/auth.md [hunk 20]
```diff
@@ -1,6 +1,6 @@
 # Authenticating in Janus
 
-To start using Janus you need to get a [Json Web Token](https://jwt.io) and provide it in every single request
+To start using the Janus adminstration API you need to get a [Json Web Token](https://jwt.io) and provide it in every single request
```
Comment (vgarvardt) [inline docs/quick_start/auth.md]: `JSON` is an abbreviation, so all letters must be capital.

File: pkg/loader/oauth_loader.go [hunk 21]
```diff
@@ -0,0 +1,148 @@
...
+	oAuthServers := m.getOAuthServers(repo)
+	m.RegisterOAuthServers(oAuthServers, repo)
+}
+
+// RegisterOAuthServers register many oauth servers
+func (m *OAuthLoader) RegisterOAuthServers(oauthServers []*oauth.Spec, repo oauth.Repository) {
+	log.Debug("Loading OAuth servers configurations")
+
+	for _, oauthServer := range oauthServers {
+		if m.subs != nil {
```
Comment (vgarvardt) [inline pkg/loader/oauth_loader.go]: Add some log here, like `log.WithField("name", oauthServer.Name).Debug("Registering OAuth server")` and same to the end of the registering the server process.

File: pkg/oauth/middleware_revoke.go [hunk 22]
```diff
@@ -6,7 +6,11 @@ import (
 	log "github.com/Sirupsen/logrus"
 )
 
-// RevokeMiddleware prevents requests to an API from exceeding a specified rate limit.
+// RevokeMiddleware is used to revoked a token from the gateway datastore.
+// If you configure Janus to use a datastore and you are not suing JWT as
```
Comment (vgarvardt) [inline pkg/oauth/middleware_revoke.go]: not *using* JWT

File: pkg/oauth/middleware_secret.go [hunk 23]
```diff
@@ -41,13 +46,13 @@ func (m *SecretMiddleware) Handler(handler http.Handler) http.Handler {
 			panic(ErrClientIDNotFound)
 		}
 
-		m.ChangeRequest(r, clientID, clientSecret)
+		m.changeRequest(r, clientID, clientSecret)
 		handler.ServeHTTP(w, r)
 	})
 }
 
 // ChangeRequest modifies the request to add the Authorization headers.
```
Comment (vgarvardt) [inline pkg/oauth/middleware_secret.go]: method name changed, but doc not

File: pkg/plugin/rate_limit.go [hunk 24]
```diff
@@ -0,0 +1,74 @@
...
+		return nil, err
+	}
+
+	return []router.Constructor{
+		limiter.NewHTTPMiddleware(limiter.NewLimiter(limiterStore, rate)).Handler,
+		middleware.NewRateLimitLogger().Handler,
+	}, nil
+}
+
+func (h *RateLimit) getLimmiterStore(policy string, prefix string) (limiter.Store, error) {
```
Comment (vgarvardt) [inline pkg/plugin/rate_limit.go]: *getLim~~m~~iterStore*

**Review by vgarvardt — CHANGES_REQUESTED** [review]

File: docs/config/proxy.md [hunk 25]
```diff
@@ -0,0 +1,11 @@
...
+
+| Configuration         | Description                                                                            |
+|----------------------------------------------------------------------------------------------------------------|
+| preserve_hosts        | Enable the [preserve host](/docs/proxy/preserve_host_property.md) definition           |
+| preserve_hosts        | Defines the [endpoint](/docs/proxy/request_uri.md) that will be exposed in Janus       |
+| upstream_url          | Defines the OAuth provider's [endpoint](/docs/proxy/upstream_url.md) for the request   |
+| strip_path            | Enable the [strip URI](/docs/proxy/strip_uri_property.md) rule on this proxy           |
+| enable_load_balancing | Enable load balancing for this proxy                                                   |
+| methods               | Defines which [methods](/docs/proxy/request_http_method.md) are enabled for this proxy |
+| hosts                 | Defines which [hosts](/docs/proxy/request_http_header.md) are enabled for this proxy   |
```
[the remark this answers is not in the document]
Comment (italolelis) [reply docs/config/proxy.md:11]: Yes the document is correct. Naming could be improved latter

File: cmd/janus/init.go [hunk 26]
```diff
@@ -48,7 +48,7 @@ func initStorage(config config.Storage) store.Store {
 	return storage
 }
 
-func initStatsdClient(config config.Stats) *stats.StatsdStatsClient {
+func initStatsdClient(config config.Stats) *stats.StatsdClient {
```
Comment (vgarvardt) [inline cmd/janus/init.go]: use `stats.Client` interface instead of `StatsdClient` implementation

File: cmd/janus/init.go [hunk 27]
```diff
@@ -59,8 +59,8 @@ func initStatsdClient(config config.Stats) *stats.StatsdStatsClient {
 		WithField("map", sectionsTestsMap.String()).
 		Debug("Setting stats second level IDs")
 
-	client := stats.NewStatsdStatsClient(config.DSN, config.Prefix)
-	client.SetHttpMetricCallback(stats.NewHasIDAtSecondLevelCallback(sectionsTestsMap))
+	client := stats.NewStatsdClient(config.DSN, config.Prefix)
```
Comment (vgarvardt) [inline cmd/janus/init.go]: `client, err := stats.NewClient(config.DSN, config.Prefix)` - currently `err` is always `nil`, but may change in the future with new backends

**Review by vgarvardt — CHANGES_REQUESTED** [review]

File: docs/SUMMARY.md [hunk 28]
```diff
@@ -20,5 +20,9 @@
     * [Request HTTP method](proxy/request_http_method.md)
     * [Routing priorities](proxy/routing_priorities.md)
     * [Conclusion](proxy/conclusion.md)
+* Plugins
+    * [OAuth](plugins/oauth.md)
+    * [Rate Limit](plugins/rate_limit.md)
+    * [CORS](plugins/cors.md)
```
Comment (vgarvardt) [inline docs/SUMMARY.md]: looks like you missed `compression` plugin description here and in `plugins/compression.md`

**Comment by vgarvardt** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/hellofresh/api-gateway/pull-request/120/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=hellofresh/api-gateway)

**Review by vgarvardt — APPROVED** [review]
